### ISSUE TITLE
Restarting processflow will cause climo and ts files to be unnecessarily re-computed

### ISSUE THREAD

**Issue by golaz** [ACME-Climate/acme_processflow#95] opened 2018-02-17 19:26 UTC
After a restart, the processflow will recompute climo and ts files even if they have already been successfully generated previously.

As a test, I restarted the processflow after it successfully completed. Here is the output:

```
11:16:15: 0001-0020 is ready
11:16:15: 0021-0040 is ready
11:16:15: 0041-0060 is ready
11:16:15: 0061-0080 is ready
11:16:15: 0081-0100 is ready
11:16:15: 0001-0050 is ready
11:16:15: 0051-0100 is ready
11:16:15: 0001-0100 is ready
11:16:17: Submitting to queue ncclimo: 0001-0020
11:16:19: ncclimo-0001-0020:4027 changed from Valid to Running
11:16:19: Submitting to queue timeseries: 0001-0020
11:16:20: timeseries-0001-0020:4028 changed from Valid to Pending
11:16:20: Submitting to queue ncclimo: 0021-0040
11:16:21: ncclimo-0021-0040:4029 changed from Valid to Pending
11:16:21: Submitting to queue timeseries: 0021-0040
11:16:21: timeseries-0021-0040:4030 changed from Valid to Pending
11:16:21: Submitting to queue ncclimo: 0041-0060
11:16:21: ncclimo-0021-0040:4029 changed from Pending to Running
11:16:21: timeseries-0021-0040:4030 changed from Pending to Running
11:16:21: ncclimo-0041-0060:4031 changed from Valid to Running
11:16:21: Submitting to queue timeseries: 0041-0060
11:16:26: timeseries-0001-0020:4028 changed from Pending to Running
11:16:31: timeseries-0041-0060:4032 changed from Valid to Running
11:17:52: All data local, turning off remote checks
11:21:10: Submitting to queue ncclimo: 0061-0080
11:21:11: timeseries-0021-0040:4030 changed from Running to Completed
11:21:11: Handling completion for timeseries: 0021-0040
11:21:11: ncclimo-0061-0080:4033 changed from Valid to Running
11:21:18: Submitting to queue timeseries: 0061-0080
11:21:18: timeseries-0041-0060:4032 changed from Running to Completed
11:21:18: Handling completion for timeseries: 0041-0060
11:21:18: timeseries-0061-0080:4034 changed from Valid to Pending
11:21:19: timeseries-0061-0080:4034 changed from Pending to Running
11:21:25: Submitting to queue ncclimo: 0081-0100
11:21:26: timeseries-0001-0020:4028 changed from Running to Completed
11:21:26: Handling completion for timeseries: 0001-0020
11:21:28: ncclimo-0081-0100:4035 changed from Valid to Running
11:26:17: timeseries-0061-0080:4034 changed from Running to Completed
11:26:17: Handling completion for timeseries: 0061-0080
11:26:26: Submitting to queue timeseries: 0081-0100
11:26:41: timeseries-0081-0100:4036 changed from Valid to Running
11:33:45: Submitting to queue ncclimo: 0001-0050
11:33:46: timeseries-0081-0100:4036 changed from Running to Completed
11:33:46: Handling completion for timeseries: 0081-0100
11:33:48: ncclimo-0001-0050:4037 changed from Valid to Running
11:44:06: Submitting to queue ncclimo: 0051-0100
11:44:06: ncclimo-0001-0020:4027 changed from Running to Completed
11:44:06: Handling completion for ncclimo: 0001-0020
11:44:09: ncclimo-0051-0100:4038 changed from Valid to Running
11:45:36: amwg-0001-0020 precomputed, skipping
11:45:36: Handling completion for amwg: 0001-0020
11:45:36: Setting up local hosting for amwg
11:47:26: Fixing permissions for /var/www/acme/acme-diags/golaz1/20180129.DECKv1b_piControl.ne30_oEC.edison/amwg/0001-0020
11:47:26: amwg hosted at https://acme-viewer.llnl.gov/golaz1/20180129.DECKv1b_piControl.ne30_oEC.edison/amwg/0001-0020
11:47:26: e3sm_diags-0001-0020 precomputed, skipping
11:47:26: Handling completion for e3sm_diags: 0001-0020
11:47:26: Setting up local hosting for e3sm_diags
11:48:33: Fixing permissions for /var/www/acme/acme-diags/golaz1/20180129.DECKv1b_piControl.ne30_oEC.edison/e3sm-diags/0001-0020
11:48:33: e3sm_diags hosted at https://acme-viewer.llnl.gov/golaz1/20180129.DECKv1b_piControl.ne30_oEC.edison/e3sm-diags/0001-0020
11:48:33: Submitting to queue ncclimo: 0001-0100
11:48:33: ncclimo-0021-0040:4029 changed from Running to Completed
11:48:33: Handling completion for ncclimo: 0021-0040
11:48:33: ncclimo-0061-0080:4033 changed from Running to Completed
11:48:33: Handling completion for ncclimo: 0061-0080
11:48:33: ncclimo-0001-0100:4039 changed from Valid to Pending
11:48:35: aprime_diags-0001-0100 precomputed, skipping
11:48:35: Handling completion for aprime_diags: 0001-0100
11:48:35: aprime_diags hosted at https://acme-viewer.llnl.gov/golaz1/20180129.DECKv1b_piControl.ne30_oEC.edison/a-prime/0001-0100/index.html
11:48:36: ncclimo-0041-0060:4031 changed from Running to Completed
11:48:36: Handling completion for ncclimo: 0041-0060
11:48:36: ncclimo-0001-0100:4039 changed from Pending to Running
11:48:49: amwg-0021-0040 precomputed, skipping
11:48:49: Handling completion for amwg: 0021-0040
11:48:49: Setting up local hosting for amwg
11:50:44: Fixing permissions for /var/www/acme/acme-diags/golaz1/20180129.DECKv1b_piControl.ne30_oEC.edison/amwg/0021-0040
11:50:44: amwg hosted at https://acme-viewer.llnl.gov/golaz1/20180129.DECKv1b_piControl.ne30_oEC.edison/amwg/0021-0040
11:50:44: e3sm_diags-0021-0040 precomputed, skipping
11:50:44: Handling completion for e3sm_diags: 0021-0040
11:50:44: Setting up local hosting for e3sm_diags
11:52:51: Fixing permissions for /var/www/acme/acme-diags/golaz1/20180129.DECKv1b_piControl.ne30_oEC.edison/e3sm-diags/0021-0040
11:52:51: e3sm_diags hosted at https://acme-viewer.llnl.gov/golaz1/20180129.DECKv1b_piControl.ne30_oEC.edison/e3sm-diags/0021-0040
11:53:19: amwg-0041-0060 precomputed, skipping
11:53:19: Handling completion for amwg: 0041-0060
11:53:20: Setting up local hosting for amwg
11:55:02: Fixing permissions for /var/www/acme/acme-diags/golaz1/20180129.DECKv1b_piControl.ne30_oEC.edison/amwg/0041-0060
11:55:02: amwg hosted at https://acme-viewer.llnl.gov/golaz1/20180129.DECKv1b_piControl.ne30_oEC.edison/amwg/0041-0060
11:55:02: e3sm_diags-0041-0060 precomputed, skipping
11:55:02: Handling completion for e3sm_diags: 0041-0060
11:55:02: Setting up local hosting for e3sm_diags
11:57:33: Fixing permissions for /var/www/acme/acme-diags/golaz1/20180129.DECKv1b_piControl.ne30_oEC.edison/e3sm-diags/0041-0060
11:57:33: e3sm_diags hosted at https://acme-viewer.llnl.gov/golaz1/20180129.DECKv1b_piControl.ne30_oEC.edison/e3sm-diags/0041-0060
11:57:56: amwg-0061-0080 precomputed, skipping
11:57:56: Handling completion for amwg: 0061-0080
11:57:56: Setting up local hosting for amwg
12:00:03: Fixing permissions for /var/www/acme/acme-diags/golaz1/20180129.DECKv1b_piControl.ne30_oEC.edison/amwg/0061-0080
12:00:03: amwg hosted at https://acme-viewer.llnl.gov/golaz1/20180129.DECKv1b_piControl.ne30_oEC.edison/amwg/0061-0080
12:00:03: e3sm_diags-0061-0080 precomputed, skipping
12:00:03: Handling completion for e3sm_diags: 0061-0080
12:00:03: Setting up local hosting for e3sm_diags
12:02:32: Fixing permissions for /var/www/acme/acme-diags/golaz1/20180129.DECKv1b_piControl.ne30_oEC.edison/e3sm-diags/0061-0080
12:02:32: e3sm_diags hosted at https://acme-viewer.llnl.gov/golaz1/20180129.DECKv1b_piControl.ne30_oEC.edison/e3sm-diags/0061-0080
12:02:58: amwg-0081-0100 precomputed, skipping
12:02:58: Handling completion for amwg: 0081-0100
12:02:59: Setting up local hosting for amwg
12:04:37: Fixing permissions for /var/www/acme/acme-diags/golaz1/20180129.DECKv1b_piControl.ne30_oEC.edison/amwg/0081-0100
12:04:40: amwg hosted at https://acme-viewer.llnl.gov/golaz1/20180129.DECKv1b_piControl.ne30_oEC.edison/amwg/0081-0100
12:04:40: e3sm_diags-0081-0100 precomputed, skipping
12:04:40: Handling completion for e3sm_diags: 0081-0100
12:04:40: Setting up local hosting for e3sm_diags
12:06:59: Fixing permissions for /var/www/acme/acme-diags/golaz1/20180129.DECKv1b_piControl.ne30_oEC.edison/e3sm-diags/0081-0100
12:06:59: e3sm_diags hosted at https://acme-viewer.llnl.gov/golaz1/20180129.DECKv1b_piControl.ne30_oEC.edison/e3sm-diags/0081-0100
12:07:49: ncclimo-0001-0050:4037 changed from Running to Completed
12:07:49: Handling completion for ncclimo: 0001-0050
12:08:10: amwg-0001-0050 precomputed, skipping
12:08:10: Handling completion for amwg: 0001-0050
12:08:10: Setting up local hosting for amwg
12:09:58: Fixing permissions for /var/www/acme/acme-diags/golaz1/20180129.DECKv1b_piControl.ne30_oEC.edison/amwg/0001-0050
12:09:58: amwg hosted at https://acme-viewer.llnl.gov/golaz1/20180129.DECKv1b_piControl.ne30_oEC.edison/amwg/0001-0050
12:09:58: e3sm_diags-0001-0050 precomputed, skipping
12:09:58: Handling completion for e3sm_diags: 0001-0050
12:09:58: Setting up local hosting for e3sm_diags
12:11:20: Fixing permissions for /var/www/acme/acme-diags/golaz1/20180129.DECKv1b_piControl.ne30_oEC.edison/e3sm-diags/0001-0050
12:11:20: e3sm_diags hosted at https://acme-viewer.llnl.gov/golaz1/20180129.DECKv1b_piControl.ne30_oEC.edison/e3sm-diags/0001-0050
12:11:20: ncclimo-0051-0100:4038 changed from Running to Completed
12:11:20: Handling completion for ncclimo: 0051-0100
12:11:32: amwg-0051-0100 precomputed, skipping
12:11:32: Handling completion for amwg: 0051-0100
12:11:33: Setting up local hosting for amwg
12:12:44: Fixing permissions for /var/www/acme/acme-diags/golaz1/20180129.DECKv1b_piControl.ne30_oEC.edison/amwg/0051-0100
12:12:44: amwg hosted at https://acme-viewer.llnl.gov/golaz1/20180129.DECKv1b_piControl.ne30_oEC.edison/amwg/0051-0100
12:12:44: e3sm_diags-0051-0100 precomputed, skipping
12:12:44: Handling completion for e3sm_diags: 0051-0100
12:12:44: Setting up local hosting for e3sm_diags
12:13:57: Fixing permissions for /var/www/acme/acme-diags/golaz1/20180129.DECKv1b_piControl.ne30_oEC.edison/e3sm-diags/0051-0100
12:13:57: e3sm_diags hosted at https://acme-viewer.llnl.gov/golaz1/20180129.DECKv1b_piControl.ne30_oEC.edison/e3sm-diags/0051-0100
12:21:56: ncclimo-0001-0100:4039 changed from Running to Completed
12:21:56: Handling completion for ncclimo: 0001-0100
12:22:05: amwg-0001-0100 precomputed, skipping
12:22:05: Handling completion for amwg: 0001-0100
12:22:05: Setting up local hosting for amwg
12:22:27: Fixing permissions for /var/www/acme/acme-diags/golaz1/20180129.DECKv1b_piControl.ne30_oEC.edison/amwg/0001-0100
12:22:27: amwg hosted at https://acme-viewer.llnl.gov/golaz1/20180129.DECKv1b_piControl.ne30_oEC.edison/amwg/0001-0100
12:22:27: e3sm_diags-0001-0100 precomputed, skipping
12:22:27: Handling completion for e3sm_diags: 0001-0100
12:22:27: Setting up local hosting for e3sm_diags
12:23:01: Fixing permissions for /var/www/acme/acme-diags/golaz1/20180129.DECKv1b_piControl.ne30_oEC.edison/e3sm-diags/0001-0100
12:23:01: e3sm_diags hosted at https://acme-viewer.llnl.gov/golaz1/20180129.DECKv1b_piControl.ne30_oEC.edison/e3sm-diags/0001-0100
12:23:02: Finishing up run
12:23:02: Performing post run cleanup
[+] All processing complete
```

**Comment by sterlingbaldwin** [comment] 2018-02-26 21:07
Found the cause for this, fix will be in the nightly build today.

**Comment by sterlingbaldwin** [comment] 2018-02-27 22:31
Fixed.

**Closed by sterlingbaldwin** 2018-02-27 22:31 UTC
Labels: bug
